"""核心常量定义"""
from enum import Enum


class Provider(str, Enum):
    """支持的 AI 模型提供商"""
    MINIMAX = "minimax"
    OPENAI = "openai"
    ANTHROPIC = "anthropic"


class MessageRole(str, Enum):
    """消息角色"""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ErrorCode(str, Enum):
    """业务错误码"""
    # 认证相关
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR"

    # 提供商相关
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT"

    # 会话相关
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_FORBIDDEN = "SESSION_FORBIDDEN"
    SESSION_EXPIRED = "SESSION_EXPIRED"

    # 消息相关
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"

    # 限流相关
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # 内部错误
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    CACHE_ERROR = "CACHE_ERROR"


# Token 限制
MAX_PROMPT_LENGTH = 100_000
MAX_COMPLETION_TOKENS = 8192

# 会话配置
DEFAULT_SESSION_TTL_DAYS = 30
MAX_SESSION_HISTORY = 100  # 最大历史消息数

# 重试配置
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY_SECONDS = 1
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_SECONDS = 60